In [23]:
import numpy as np
class MLP:
    
    def __init__(self):
        pass
    
    def forward(self,X):
        '''receives input of n*input_units and returns output of d*output_units
            In this case, it returns same 
        '''
        return X
    
    def backward(self,X,grad_output):
        
        return X
    
class RELU(MLP):
    def __init__(Layer):
        pass
    
    def forward(self,input):
        relu_forward = np.maximum(0,input)
        return relu_forward
    
    def backward(self,input,grad_output):
        relu_grad = input >0
        return grad_output *relu_grad
    

In [4]:
np.eye(1,2)

array([[1., 0.]])

In [17]:
x = np.random.randn(2,3)

In [18]:
np.maximum(0,x[0])

array([2.02879283, 0.        , 0.37021982])

In [19]:
x

array([[ 2.02879283, -1.04588148,  0.37021982],
       [ 1.15851949, -1.28931149,  0.09323267]])

In [22]:
x*(x>0)

array([[ 2.02879283, -0.        ,  0.37021982],
       [ 1.15851949, -0.        ,  0.09323267]])